name: RenView
description: Restaurant review service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  json_annotation:
  functional_data:
  plain_optional:
  rxdart:
  provider:

  communicator:
    path: pkgs/communicator
  persistency:
    path: pkgs/persistency
  login:
    path: pkgs/login
  utils:
    path: pkgs/utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  functional_data_generator:
  json_serializable:

flutter:
  uses-material-design: true
