name: login
description: Provides login UI.
version: 0.0.1
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  redux:
  functional_data:
  provider:

  communicator:
    path: ../../pkgs/communicator
  utils:
    path: ../../pkgs/utils


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  functional_data_generator:

flutter:
